  json.extract! business,
            :id,
            :name,
            :website,
            :category,
            :address,
            :city,
            :state,
            :zip_code,
            :phone_number,
            :lat,
            :lng